---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: lontara
# description will be included in the image's metadata
description: Secure and Easy to Use Distro

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: os-release
    properties:
      ID: lontara
      ID_LIKE: fedora
      NAME: Lontara
      PRETTY_NAME: Lontara
      LOGO: lontara
      DEFAULT_HOSTNAME: lontara
      BUG_REPORT_URL: https://github.com/prastowoagungwidodo/lontara/issues
      HOME_URL: https://github.com/prastowoagungwidodo/lontara
  - type: dnf
    repos:
      copr:
        - atim/starship
      files:
        - https://repo.secureblue.dev/secureblue.repo
    install:
      packages:
        - starship
        - trivalent
        - zsh
        - usbguard
        - usbguard-notifier
        - usbguard-selinux
        - adw-gtk3-theme
        - 7zip
        - 7zip-standalone-all
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: false # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.gnome.Showtime
          - org.gnome.Calendar
          - org.gnome.clocks
          - org.gnome.font-viewer
          - org.gnome.Weather
          - org.gnome.Papers
          - org.gnome.Characters
          - org.gnome.TextEditor
          - org.gtk.Gtk3theme.adw-gtk3
          - org.gtk.Gtk3theme.adw-gtk3-dark
          - com.github.tchx84.Flatseal
          - com.mattjakeman.ExtensionManager
        remove:
          - org.gnome.Extensions
  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono
  - type: gnome-extensions
    install:
      - 307
      - 615
      - 7048
  - type: gschema-overrides
  - type: systemd
    system:
      enabled:
        - usbguard.service
    user:
      enabled:
        - usbguard-notifier.service
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry
  - type: script
    scripts:
      - lontara-customize.sh
      - selinux.sh
  - type: kargs
    arch: x86_64, aarch64
    kargs:
      - loglevel=0
      - module.sig_enforce=1
      - page_alloc.shuffle=1
      - proc_mem.force_override=ptrace
      - pti=on
      - random.trust_bootloader=off
      - random.trust_cpu=off
      - randomize_kstack_offset=on
      - rd.shell=0
      - rd.emergency=halt
      - slab_nomerge
      - spec_store_bypass_disable=on
      - spectre_v2=on
      - ssbd=force-on
      - vdso32=0
      - vsyscall=none
      - init_on_alloc=1
      - init_on_free=1
      - iommu=force
      - intel_iommu=on
      - iommu.passthrough=0
      - iommu.strict=1
      - kvm-intel.vmentry_l1d_flush=always
      - kvm.mitigate_smt_rsb=1
      - l1d_flush=on
      - l1tf=full,force
      - lockdown=confidentiality
  - type: initramfs
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
